# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62bd032c0b9d9f84a4c4e1ccf20cb0245895591472a9f0ca42f42dcfa15a30c3250f0bc4ae76a97b2648a936777c8178b278c0ea320b084ca24b61b204683720

test:
  secret_key_base: 796346571fa4ccf87a69d633a54feb6d72def8561deca43deb10f525f14e28c5be16d02e1bb7ea3eba9aa47ea6ba5a8ee9482b25d0b9645069703382f424a2ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
